# Baseline H16 — robustez *full-core*

Fecha: `2026-05-31`

Este es el primer experimento "grande" del proyecto, y el que decide si merece la pena
seguir. La pregunta es directa: el baseline direccional a 16 s (`delta_ticks_16s`),
¿encuentra señal que **aguante** cuando ampliamos datos, folds y *ablations*, o era un
espejismo de una muestra corta?

Es un cuaderno de **ejecución larga autorizada**. La lógica pesada vive en
`scripts/experiments/baseline_v0_full_core_robustness.py`, para que sea reproducible y
fácil de relanzar; aquí cargamos los resultados y los leemos.

## Contrato del experimento

- SQLite oficial en **solo lectura**.
- Target principal: `delta_ticks_16s`, banda de `1 tick`.
- Entrenamiento por *token-frame*; evaluación y acción por *market-frame* (para no
  contar dos veces el mismo instante del mercado binario).
- Modelos **sobrios**: regresión logística balanceada y un HGB pequeño balanceado.
  Nada de redes todavía: primero hay que probar que hay señal.
- Validación con **folds temporales + test terminal** sellado.
- Sin Coinbase, *depth*, Deribit, *sidecars* ni contexto no auditado como feature
  fuerte: empezamos con lo mínimo defendible.

## Ejecucion

Esta celda puede tardar. Genera cache Parquet experimental en `data/experiments/baseline_v0_full_core_robustness/` y resultados CSV/JSON.

In [1]:
%run scripts/experiments/baseline_v0_full_core_robustness.py

DB: D:\polymarket_btc_probe_official_v1\polymarket_week.sqlite3 exists=True size_gib=68.95

id range 1..2,499,840; qualified core sessions=2,590

C:\Users\ftpx\Desktop\Recolector\edgerunner\scripts\experiments\baseline_v0_full_core_robustness.py:394: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "created_at_utc": pd.Timestamp.utcnow().isoformat(),

chunk 000 ids 1-100,000: raw=93,928 support=92,092 sec=253.8

chunk 001 ids 100,001-200,000: raw=95,008 support=92,370 sec=346.3

chunk 002 ids 200,001-300,000: raw=93,892 support=92,428 sec=267.0

chunk 003 ids 300,001-400,000: raw=93,970 support=91,030 sec=268.3

chunk 004 ids 400,001-500,000: raw=93,888 support=93,248 sec=262.0

chunk 005 ids 500,001-600,000: raw=92,060 support=89,588 sec=261.4

chunk 006 ids 600,001-700,000: raw=95,008 support=94,738 sec=269.7

chunk 007 ids 700,001-800,000: raw=95,008 support=94,814 sec=265.8

chunk 008 ids 800,001-900,000: raw=95,008 support=94,906 sec=268.2

chunk 009 ids 900,001-1,000,000: raw=95,008 support=95,004 sec=263.8

chunk 010 ids 1,000,001-1,100,000: raw=94,096 support=93,892 sec=265.9

chunk 011 ids 1,100,001-1,200,000: raw=94,048 support=93,890 sec=261.2

chunk 012 ids 1,200,001-1,300,000: raw=95,008 support=94,726 sec=265.9

chunk 013 ids 1,300,001-1,400,000: raw=95,008 support=94,868 sec=266.9

chunk 014 ids 1,400,001-1,500,000: raw=93,184 support=92,930 sec=261.5

chunk 015 ids 1,500,001-1,600,000: raw=95,008 support=94,770 sec=266.8

chunk 016 ids 1,600,001-1,700,000: raw=95,008 support=94,746 sec=266.2

chunk 017 ids 1,700,001-1,800,000: raw=94,960 support=94,796 sec=265.2

chunk 018 ids 1,800,001-1,900,000: raw=95,008 support=94,762 sec=264.6

chunk 019 ids 1,900,001-2,000,000: raw=94,096 support=93,850 sec=261.3

chunk 020 ids 2,000,001-2,100,000: raw=94,096 support=93,846 sec=263.9

chunk 021 ids 2,100,001-2,200,000: raw=95,008 support=94,844 sec=267.7

chunk 022 ids 2,200,001-2,300,000: raw=94,926 support=94,636 sec=270.0

chunk 023 ids 2,300,001-2,400,000: raw=94,960 support=94,740 sec=273.1

chunk 024 ids 2,400,001-2,499,840: raw=93,936 support=93,770 sec=317.8

loaded cache rows=2,345,284 cols=124 sec=11.1

C:\Users\ftpx\Desktop\Recolector\edgerunner\scripts\experiments\baseline_v0_full_core_robustness.py:846: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["terminal_split"] = df["session_day"].astype(str).map(assign_terminal_split).astype("category")

complete market frames=1,172,642/1,172,642 (100.00%)

rule summary
                label              split  coverage_pct  hit_up_pct  wrong_down_pct  net_visible_mean
rule_pm_perp_both_pos validation_initial        7.7875     48.4248         15.6861            1.1954
rule_pm_spot_both_pos validation_initial        7.9609     47.9789         16.3131            1.1033
rule_pm_perp_both_pos      test_terminal        6.3236     44.6191         18.0258            0.6500
rule_pm_spot_both_pos      test_terminal        6.2842     45.9190         17.8327            0.6405

Fold F1: train=567,308 val=362,442 purged=732

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

  logreg_balanced: bal_acc=0.5744 macro_f1=0.5707 th=0.45 actions=7,553.0 hit=60.62% wrong=21.75% net=1.408

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

  hgb_balanced_small: bal_acc=0.6021 macro_f1=0.5922 th=0.55 actions=2,152.0 hit=77.97% wrong=10.41% net=4.485

Fold F2: train=930,482 val=343,116 purged=0

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

  logreg_balanced: bal_acc=0.5740 macro_f1=0.5723 th=0.60 actions=3,608.0 hit=62.58% wrong=22.48% net=1.768

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

  hgb_balanced_small: bal_acc=0.6004 macro_f1=0.5954 th=0.55 actions=2,797.0 hit=71.33% wrong=14.66% net=2.978

Fold F3: train=1,272,990 val=321,114 purged=608

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

  logreg_balanced: bal_acc=0.5794 macro_f1=0.5789 th=0.55 actions=2,805.0 hit=64.21% wrong=23.81% net=2.120

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

  hgb_balanced_small: bal_acc=0.6072 macro_f1=0.6047 th=0.55 actions=2,238.0 hit=71.45% wrong=13.36% net=2.518

Fold F4: train=1,594,712 val=313,860 purged=0

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

  logreg_balanced: bal_acc=0.5862 macro_f1=0.5847 th=0.60 actions=1,704.0 hit=68.37% wrong=20.48% net=3.021

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

  hgb_balanced_small: bal_acc=0.6125 macro_f1=0.6087 th=0.50 actions=3,712.0 hit=71.58% wrong=12.02% net=2.607

Final run logreg_balanced__full_v0: train=1,594,712 val=313,860 test=436,712

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

  val_bal=0.5862 test_bal=0.5713 th=0.60 test_actions=1,336.0 hit=55.24% wrong=26.50% net=1.136

Final run hgb_balanced_small__pm_only: train=1,594,712 val=313,860 test=436,712

  val_bal=0.5729 test_bal=0.5628 th=-0.05 test_actions=217,487.0 hit=32.20% wrong=18.74% net=-0.291

Final run hgb_balanced_small__pm_time: train=1,594,712 val=313,860 test=436,712

  val_bal=0.6032 test_bal=0.5929 th=-0.05 test_actions=217,948.0 hit=32.24% wrong=18.66% net=-0.289

Final run hgb_balanced_small__pm_perp_time: train=1,594,712 val=313,860 test=436,712

  val_bal=0.6109 test_bal=0.5971 th=0.50 test_actions=3,721.0 hit=66.25% wrong=10.70% net=1.610

Final run hgb_balanced_small__pm_spot_time: train=1,594,712 val=313,860 test=436,712

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

  val_bal=0.6098 test_bal=0.5968 th=0.50 test_actions=3,333.0 hit=64.27% wrong=11.19% net=1.342

Final run hgb_balanced_small__full_v0: train=1,594,712 val=313,860 test=436,712

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

  val_bal=0.6125 test_bal=0.5976 th=0.50 test_actions=3,802.0 hit=66.91% wrong=11.31% net=1.599

Final run hgb_balanced_small__full_no_microprice: train=1,594,712 val=313,860 test=436,712

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

  val_bal=0.5953 test_bal=0.5768 th=0.50 test_actions=1,371.0 hit=75.93% wrong=11.31% net=3.510

Final run hgb_balanced_small__full_plus_quality_masks: train=1,594,712 val=313,860 test=436,712

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

  val_bal=0.6125 test_bal=0.5975 th=0.50 test_actions=3,779.0 hit=66.87% wrong=11.43% net=1.597

Final run hgb_balanced_small__full_plus_intertemporal: train=1,594,712 val=313,860 test=436,712

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

  val_bal=0.6124 test_bal=0.5980 th=0.50 test_actions=3,864.0 hit=66.64% wrong=10.71% net=1.559

Best label: hgb_balanced_small__full_no_microprice

Permutation importance on 30,000 validation rows for hgb_balanced_small__full_no_microprice

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

C:\Users\ftpx\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\impute\_base.py:641: UserWarning: Skipping features without any observed values: ['external_realized_vol_bps_15s']. At least one non-missing value is needed for imputation with strategy='median'.
  warnings.warn(

Permutation seconds=26.0

BASELINE V0 FULL-CORE ROBUSTNESS SUMMARY

- rows: 2,345,284

- complete market frames: 1,172,642/1,172,642 (100.00%)

Target distribution:

target_3c_16s_1tick     pct
               flat 47.3387
                 up 26.4383
               down 26.2230

Final ablations:

        model_kind             feature_set  selected_threshold  test_balanced_accuracy  test_macro_f1  test_action_actions  test_action_coverage_pct  test_action_hit_up_pct  test_action_wrong_down_pct  test_action_net_visible_mean  test_action_net_positive_pct
hgb_balanced_small      full_no_microprice                0.50                  0.5768         0.5738               1371.0                    0.6279                 75.9300                     11.3056                        3.5101                       76.2217
hgb_balanced_small            pm_perp_time                0.50                  0.5971         0.5912               3721.0                    1.7041                 66.2456                     10.6960                        1.6097                       67.1325
hgb_balanced_small                 full_v0                0.50                  0.5976         0.5918               3802.0                    1.7412                 66.9122                     11.3098                        1.5987                       67.8853
hgb_balanced_small full_plus_quality_masks                0.50                  0.5975         0.5917               3779.0                    1.7307                 66.8695                     11.4316                        1.5973                       67.9809
hgb_balanced_small full_plus_intertemporal                0.50                  0.5980         0.5922               3864.0                    1.7696                 66.6408                     10.7143                        1.5592                       67.7536
hgb_balanced_small            pm_spot_time                0.50                  0.5968         0.5907               3333.0                    1.5264                 64.2664                     11.1911                        1.3418                       65.0465
   logreg_balanced                 full_v0                0.60                  0.5713         0.5691               1336.0                    0.6118                 55.2395                     26.4970                        1.1359                       53.0689
hgb_balanced_small                 pm_time               -0.05                  0.5929         0.5862             217948.0                   99.8131                 32.2366                     18.6590                       -0.2892                       33.3052
hgb_balanced_small                 pm_only               -0.05                  0.5628         0.5569             217487.0                   99.6020                 32.1992                     18.7368                       -0.2914                       33.1611

Best label: hgb_balanced_small__full_no_microprice

C:\Users\ftpx\Desktop\Recolector\edgerunner\scripts\experiments\baseline_v0_full_core_robustness.py:1176: Pandas4Warning: Timestamp.utcnow is deprecated and will be removed in a future version. Use Timestamp.now('UTC') instead.
  "created_at_utc": pd.Timestamp.utcnow().isoformat(),

## Resultados cargados

Las celdas siguientes leen los CSV que generó el script, para que el cuaderno se pueda
navegar sin tener que mirar todo el log de ejecución:

- `final_summary.csv` — el resumen por familia de features (¿qué bloque aporta?);
- `walkforward_summary.csv` — estabilidad a lo largo de los folds temporales;
- `rule_summary.csv` — el resultado de la regla de decisión;
- `best_model_segments.csv` — desglose por segmentos del mejor modelo;
- `best_model_permutation_importance.csv` — qué features pesan de verdad
  (importancia por permutación, interpretabilidad ligera).

In [2]:
from pathlib import Path
import json
import pandas as pd
from IPython.display import display

RESULTS = Path('data/experiments/baseline_v0_full_core_robustness/results')
summary = json.loads((RESULTS / 'summary.json').read_text(encoding='utf-8'))
print(json.dumps(summary, indent=2)[:4000])

{
  "created_at_utc": "2026-05-31T01:18:21.267006+00:00",
  "rows": 2345284,
  "complete_market_frames": 1172642,
  "market_frames": 1172642,
  "cache_dir": "C:\\Users\\ftpx\\Desktop\\Recolector\\edgerunner\\data\\experiments\\baseline_v0_full_core_robustness\\baseline_v0_core_h16_parquet",
  "results_dir": "C:\\Users\\ftpx\\Desktop\\Recolector\\edgerunner\\data\\experiments\\baseline_v0_full_core_robustness\\results",
  "best_label": "hgb_balanced_small__full_no_microprice",
  "best_final": {
    "model_kind": "hgb_balanced_small",
    "feature_set": "full_no_microprice",
    "selected_threshold": 0.5,
    "validation_selection_score": 4.069775893309294,
    "fit_seconds": 31.77093267440796,
    "val_n": 313860,
    "val_accuracy": 0.625428535015612,
    "val_balanced_accuracy": 0.595288481498018,
    "val_macro_f1": 0.5931719699607433,
    "val_score_delta_spearman": 0.19676685609135672,
    "test_n": 436712,
    "test_accuracy": 0.6124242063419371,
    "test_balanced_accuracy": 0.5768475517443655,
    "test_macro_f1": 0.573822785705303,
    "test_score_delta_spearman": 0.1674908988642538,
    "val_action_complete_frames": 156930.0,
    "val_action_actions": 2227.0,
    "val_action_coverage_pct": 1.419104059134646,
    "val_action_hit_up_pct": 78.31162999550966,
    "val_action_flat_pct": 9.788953749438708,
    "val_action_wrong_down_pct": 11.899416255051639,
    "val_action_delta_mean": 5.137179851531982,
    "val_action_delta_median": 3.0,
    "val_action_cost_median": 0.7093285322189331,
    "val_action_net_visible_mean": 4.353070259094238,
    "val_action_net_visible_median": 2.44028902053833,
    "val_action_net_positive_pct": 78.26672653794343,
    "val_action_score_median": 0.5480445550952456,
    "test_action_complete_frames": 218356.0,
    "test_action_actions": 1371.0,
    "test_action_coverage_pct": 0.6278737474582791,
    "test_action_hit_up_pct": 75.92997811816193,
    "test_action_flat_pct": 12.76440554339898,
    "test_action_wrong_down_pct": 11.305616338439094,
    "test_action_delta_mean": 4.233041763305664,
    "test_action_delta_median": 3.0,
    "test_action_cost_median": 0.6985153555870056,
    "test_action_net_visible_mean": 3.5100722312927246,
    "test_action_net_visible_median": 2.25907564163208,
    "test_action_net_positive_pct": 76.2217359591539,
    "test_action_score_median": 0.5372530037580043
  },
  "notebook_wall_seconds": 10031.440230369568
}

In [3]:
final_summary = pd.read_csv(RESULTS / 'final_summary.csv')
cols = ['model_kind','feature_set','selected_threshold','test_balanced_accuracy','test_macro_f1','test_action_actions','test_action_coverage_pct','test_action_hit_up_pct','test_action_wrong_down_pct','test_action_net_visible_mean','test_action_net_positive_pct','fit_seconds']
display(final_summary[cols].round(4))

,model_kind,feature_set,selected_threshold,test_balanced_accuracy,test_macro_f1,test_action_actions,test_action_coverage_pct,test_action_hit_up_pct,test_action_wrong_down_pct,test_action_net_visible_mean,test_action_net_positive_pct,fit_seconds
0,hgb_balanced_small,full_no_microprice,0.50,0.5768,0.5738,1371.0,0.6279,75.9300,11.3056,3.5101,76.2217,31.7709
1,hgb_balanced_small,pm_perp_time,0.50,0.5971,0.5912,3721.0,1.7041,66.2456,10.6960,1.6097,67.1325,33.8145
2,hgb_balanced_small,full_v0,0.50,0.5976,0.5918,3802.0,1.7412,66.9122,11.3098,1.5987,67.8853,38.2068
3,hgb_balanced_small,full_plus_quality_masks,0.50,0.5975,0.5917,3779.0,1.7307,66.8695,11.4316,1.5973,67.9809,44.9589
4,hgb_balanced_small,full_plus_intertemporal,0.50,0.5980,0.5922,3864.0,1.7696,66.6408,10.7143,1.5592,67.7536,41.9515
5,hgb_balanced_small,pm_spot_time,0.50,0.5968,0.5907,3333.0,1.5264,64.2664,11.1911,1.3418,65.0465,31.1255
6,logreg_balanced,full_v0,0.60,0.5713,0.5691,1336.0,0.6118,55.2395,26.4970,1.1359,53.0689,29.7426
7,hgb_balanced_small,pm_time,-0.05,0.5929,0.5862,217948.0,99.8131,32.2366,18.6590,-0.2892,33.3052,25.0143
8,hgb_balanced_small,pm_only,-0.05,0.5628,0.5569,217487.0,99.6020,32.1992,18.7368,-0.2914,33.1611,16.7821

In [4]:
walk = pd.read_csv(RESULTS / 'walkforward_summary.csv')
cols = ['fold','model_kind','balanced_accuracy','macro_f1','selected_threshold','actions','coverage_pct','hit_up_pct','wrong_down_pct','net_visible_mean','net_positive_pct','fit_seconds']
display(walk[cols].round(4))

  fold          model_kind  balanced_accuracy  macro_f1  selected_threshold  actions  coverage_pct  hit_up_pct  wrong_down_pct  net_visible_mean  net_positive_pct  fit_seconds
0   F1     logreg_balanced             0.5744    0.5707                0.45   7553.0        4.1678     60.6249         21.7529            1.4079           57.5003       7.6644
1   F1  hgb_balanced_small             0.6021    0.5922                0.55   2152.0        1.1875     77.9740         10.4089            4.4852           78.0204      15.6729
2   F2     logreg_balanced             0.5740    0.5723                0.60   3608.0        2.1031     62.5831         22.4778            1.7679           58.6475      17.0343
3   F2  hgb_balanced_small             0.6004    0.5954                0.55   2797.0        1.6304     71.3264         14.6586            2.9780           72.0415      21.2273
4   F3     logreg_balanced             0.5794    0.5789                0.55   2805.0        1.7470     64.2068         23.8146            2.1198           61.8895      22.9451
5   F3  hgb_balanced_small             0.6072    0.6047                0.55   2238.0        1.3939     71.4477         13.3601            2.5184           71.8945      30.1992
6   F4     logreg_balanced             0.5862    0.5847                0.60   1704.0        1.0858     68.3685         20.4812            3.0207           65.2582      29.3405
7   F4  hgb_balanced_small             0.6125    0.6087                0.50   3712.0        2.3654     71.5787         12.0151            2.6067           72.4138      37.8574

In [5]:
rule = pd.read_csv(RESULTS / 'rule_summary.csv')
cols = ['label','split','complete_frames','actions','coverage_pct','hit_up_pct','flat_pct','wrong_down_pct','delta_mean','cost_median','net_visible_mean','net_positive_pct']
display(rule[cols].round(4))

,label,split,complete_frames,actions,coverage_pct,hit_up_pct,flat_pct,wrong_down_pct,delta_mean,cost_median,net_visible_mean,net_positive_pct
0,rule_pm_perp_both_pos,validation_initial,156930,12221,7.7875,48.4248,35.8890,15.6861,1.9552,0.7142,1.1954,49.7259
1,rule_pm_spot_both_pos,validation_initial,156930,12493,7.9609,47.9789,35.7080,16.3131,1.8618,0.7142,1.1033,49.3316
2,rule_pm_perp_both_pos,test_terminal,218356,13808,6.3236,44.6191,37.3552,18.0258,1.3756,0.7041,0.6500,46.1616
3,rule_pm_spot_both_pos,test_terminal,218356,13722,6.2842,45.9190,36.2484,17.8327,1.3692,0.7093,0.6405,47.5660

In [6]:
segments_path = RESULTS / 'best_model_segments.csv'
if segments_path.exists():
    seg = pd.read_csv(segments_path)
    display(seg.round(4))

,segment_type,segment,actions,coverage_within_actions_pct,hit_up_pct,flat_pct,wrong_down_pct,delta_mean,delta_median,cost_median,net_visible_mean,net_positive_pct
0,cost_bucket,low_cost,457,33.3333,76.1488,15.3173,8.5339,3.4059,2.0,0.5597,2.8407,76.8053
1,cost_bucket,mid_cost,457,33.3333,75.9300,14.2232,9.8468,4.6904,3.0,0.6985,3.9972,77.0241
2,cost_bucket,high_cost,457,33.3333,75.7112,8.7527,15.5361,4.6028,3.5,0.7396,3.6923,74.8359
3,phase_bucket,early,766,55.8716,73.6292,14.0992,12.2715,4.2774,3.0,0.7107,3.5314,74.0209
4,phase_bucket,middle,473,34.5004,78.0127,11.8393,10.1480,4.1882,2.0,0.6745,3.5005,78.4355
5,phase_bucket,late,132,9.6280,81.8182,8.3333,9.8485,4.1364,3.0,0.6027,3.4204,81.0606
6,practical_dead_early,1,1371,100.0000,75.9300,12.7644,11.3056,4.2330,3.0,0.6985,3.5101,76.2217
7,score_bucket,q1_low_score,343,25.0182,70.2624,18.0758,11.6618,2.9825,2.0,0.6918,2.2405,70.8455
8,score_bucket,q2,343,25.0182,70.2624,13.7026,16.0350,2.8717,2.0,0.6987,2.1801,70.8455
9,score_bucket,q4_high_score,343,25.0182,85.7143,8.1633,6.1224,6.8324,5.0,0.6930,6.0979,85.7143
10,score_bucket,q3,342,24.9453,77.4854,11.1111,11.4035,4.2456,3.0,0.7071,3.5218,77.4854
11,temporality,1h,716,52.2247,72.7654,18.2961,8.9385,2.5978,2.0,0.6930,1.8968,72.9050
12,temporality,15m,436,31.8016,79.5872,8.2569,12.1560,5.0596,4.0,0.6930,4.3506,80.5046
13,temporality,5m,219,15.9737,78.9954,3.6530,17.3516,7.9338,6.0,0.7142,7.1111,78.5388
14,tradability_status,practical_dead_early,1371,100.0000,75.9300,12.7644,11.3056,4.2330,3.0,0.6985,3.5101,76.2217
15,window_phase,live,1371,100.0000,75.9300,12.7644,11.3056,4.2330,3.0,0.6985,3.5101,76.2217

In [7]:
perm_path = RESULTS / 'best_model_permutation_importance.csv'
coef_path = RESULTS / 'logreg_top_coefficients.csv'
if perm_path.exists():
    display(pd.read_csv(perm_path).head(30).round(6))
if coef_path.exists():
    display(pd.read_csv(coef_path).head(30).round(6))

                                   feature  importance_mean  importance_std
0                seconds_from_window_start         0.187013        0.001959
1          perp_mid_return_bps_2s_oriented         0.017771        0.000508
2                           polymarket_mid         0.016704        0.001138
3                        boundary_distance         0.012955        0.000517
4                    seconds_to_window_end         0.007379        0.000037
5          perp_mid_return_bps_8s_oriented         0.006960        0.002042
6                 visible_entry_cost_ticks         0.006004        0.000175
7                       mid_delta_ticks_8s         0.005157        0.001673
8      external_mid_return_bps_2s_oriented         0.004099        0.001094
9                              temporality         0.003138        0.000234
10                         window_progress         0.002266        0.000469
11  perp_mark_price_return_bps_2s_oriented         0.001819        0.000333
12                      mid_delta_ticks_2s         0.001646        0.000192
13     external_mid_return_bps_8s_oriented         0.000850        0.000938
14                            spread_ticks         0.000802        0.000256
15        perp_taker_buy_sell_log_oriented         0.000622        0.000264
16  perp_mark_price_return_bps_8s_oriented         0.000463        0.000429
17            external_realized_vol_bps_5s         0.000458        0.000458
18                              perp_basis         0.000292        0.000208
19                               tick_size         0.000241        0.000139
20                perp_realized_vol_bps_5s         0.000112        0.000092
21                  spot_perp_mark_gap_bps         0.000086        0.000197
22       external_trade_imbalance_oriented         0.000083        0.000290
23                   spot_perp_mid_gap_bps         0.000048        0.000074
24                            phase_bucket         0.000029        0.000020
25                            window_phase         0.000013        0.000352
26             perp_open_interest_delta_8s         0.000011        0.000021
27           external_realized_vol_bps_15s         0.000000        0.000000
28                            fee_rate_bps         0.000000        0.000000
29                     perp_basis_delta_8s         0.000000        0.000000

                 source class                            feature  importance  abs_importance
0   logreg_coef_abs_top  flat               num__window_progress   -1.076710        1.076710
1   logreg_coef_abs_top  flat         cat__window_phase_prestart    0.930502        0.930502
2   logreg_coef_abs_top  flat             cat__window_phase_live   -0.755864        0.755864
3   logreg_coef_abs_top  flat             cat__phase_bucket_late    0.546227        0.546227
4   logreg_coef_abs_top  down               num__window_progress    0.538967        0.538967
5   logreg_coef_abs_top    up               num__window_progress    0.537743        0.537743
6   logreg_coef_abs_top  flat      num__visible_entry_cost_ticks   -0.526433        0.526433
7   logreg_coef_abs_top  down         cat__window_phase_prestart   -0.469796        0.469796
8   logreg_coef_abs_top    up         cat__window_phase_prestart   -0.460706        0.460706
9   logreg_coef_abs_top  flat            cat__phase_bucket_early   -0.431361        0.431361
10  logreg_coef_abs_top  flat                  num__spread_ticks    0.407879        0.407879
11  logreg_coef_abs_top  flat     num__seconds_from_window_start    0.379996        0.379996
12  logreg_coef_abs_top    up             cat__window_phase_live    0.378488        0.378488
13  logreg_coef_abs_top  down             cat__window_phase_live    0.377376        0.377376
14  logreg_coef_abs_top  flat                cat__temporality_5m   -0.282463        0.282463
15  logreg_coef_abs_top  down      num__visible_entry_cost_ticks    0.278541        0.278541
16  logreg_coef_abs_top  down             cat__phase_bucket_late   -0.275376        0.275376
17  logreg_coef_abs_top    up             cat__phase_bucket_late   -0.270852        0.270852
18  logreg_coef_abs_top  flat             num__boundary_distance   -0.269613        0.269613
19  logreg_coef_abs_top  flat         num__seconds_to_window_end    0.267826        0.267826
20  logreg_coef_abs_top    up      num__visible_entry_cost_ticks    0.247892        0.247892
21  logreg_coef_abs_top  flat               cat__temporality_15m    0.237078        0.237078
22  logreg_coef_abs_top  flat                cat__temporality_1h    0.220023        0.220023
23  logreg_coef_abs_top  down                  num__spread_ticks   -0.219273        0.219273
24  logreg_coef_abs_top    up            cat__phase_bucket_early    0.216909        0.216909
25  logreg_coef_abs_top  down            cat__phase_bucket_early    0.214453        0.214453
26  logreg_coef_abs_top    up  num__microprice_gap_ticks_clipped    0.195087        0.195087
27  logreg_coef_abs_top  down  num__microprice_gap_ticks_clipped   -0.192689        0.192689
28  logreg_coef_abs_top  down     num__seconds_from_window_start   -0.190460        0.190460
29  logreg_coef_abs_top    up     num__seconds_from_window_start   -0.189535        0.189535

## Lectura

Lo que sale de aquí, en una frase: **hay señal y aguanta**. El bloque PM + perp es el
que manda (ni Polymarket solo ni el reloj solo bastan), y la señal sobrevive a los
folds temporales, no solo al corte único. Eso da un `GO` para seguir explorando
*offline*, no para montar un bot.

La permutación de importancias confirma que el modelo se apoya en variables con sentido
(estado local del token + referencia del perp), no en artefactos. La decisión completa,
con sus números, está en `docs/BASELINE_V0_FULL_CORE_ROBUSTNESS.md`. Este cuaderno
queda como evidencia ejecutable del paso: extracción, validación, *ablations*, folds,
segmentos e interpretabilidad.